import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Body from "./Body";
import Navigation from "./nav/Navigation";
import Footer from "./Footer";

export default function Home() {
  return (
    <>
      <Navigation />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.grid}>
            <Body />
          </div>
        </main>
      </div>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </>
  );
}
